### ISSUE TITLE
Apostrophe letter modifiers (U+02BC, U+02BD) overlap the next character in Noto Serif

### ISSUE THREAD

**Issue by verdy-p** [notofonts/latin-greek-cyrillic#431]
## Defect Report

With "Noto Serif" (not with "Noto Sans"):
The Apostrophe letter modifier (U+02BC) currently overlaps the next character, apparently it is incorrectly using a zero-width advance.

### Fonts
  NotoSerif-Bold.tff
  NotoSerif-BoldItalic.tff
  NotoSerif-Italic.tff
  NotoSerif-Regular.tff
 
### Where the font came from, and when
  Site: https://fonts.google.com/noto/specimen/Noto+Serif
  Date: 2023-05-29

### Font Version
  1.03 (current release in https://fonts.google.com/noto)

### OS name and version
  Not relevant, but seen on Windows 11, Windows 10, Android 10+.

### Application name and version
  Not specific.

### Issue
  1. Install basic "Noto Serif" fonts. Open "https://en.wikipedia.org/wiki/Q%CA%BCeqchi%CA%BC_language" with Google Chrome (current release). Look at the page title.
  2. Result: apostrophes are overlapping the following 'e' or the following space (as if there was none) in the page title "Qʼeqchiʼ language"; these apostrophes are rendered as if they were non-spacing diacritics (the're not! even if these are "modifier letters"). This makes some texts unreadable (not jsut page titles on Wikipedia, but many sites using serif style for the text of their main content; serif style is the default ni most browsers, and for many facsimiles of books, it starts being popular again even on displays wih HiDPI resolutions; it is used very often for all printed documents).
    You may try using Chrome's console to "inspect" the page title, and force a new font by typing a custom stylesheet rule for the `<h1>` element showing the page title (e.g. force `font-family:'Noto Sans'`, or `font-family:'Noto Serif'` in the "Styles" panel of the webbrowser). Then change the letter case, of 'e' into 'E', you'll see the apostrope overlapping this 'E' (may be an horizontal kerning rule has the incorrect sign/direction).
  3. Expected: apostrophes should not overlap in the page title (which uses serif style), just like they correctly don't overlap in the sans-serif style below.
    And these apostrophe modifier letters U+02BC should be *slightly* kerned to the left, next to the *previous* character that it logically modifies (to denote an ejective consonnant or a trailing glottal stop after a vowel), not the *next* one on the right, but possibly with some additional small trailing gap on the right (especially before quotation marks).
    This bug does not occur with the regular APOSTROPHE-QUOTE U+2019, used either as a common sign (for quotation marks), or as a common orthographic mark of elision (in French or Italian with fine typography, and even in English in "it's" for "it is", "don't" for "do not", or in genitives like "John's"), but that *may* include a small additional trailing gap (e.g. before curly quotation marks) but should avoid reducing their leading gap by kerning).

### Screenshot
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/1387035/3997d9dd-357a-44e0-ab92-66ffe9b7ba81)

The same bug occurs with version 2.012 loaded from https://notofonts.github.io/latin-greek-cyrillic/

**Comment by verdy-p** [comment]
See also the apprently related issue https://github.com/notofonts/latin-greek-cyrillic/issues/393

**Comment by verdy-p** [comment]
Similar problem for the reverse apostrophe with "Noto Serif" in the "Saʽidi Arabic" title of https://en.wikipedia.org/wiki/Sa%CA%BDidi_Arabic
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/1387035/7f8ee9d7-7ed3-4d1e-992d-49965bc9999d)

**Comment by simoncozens** [comment]
> 1.03 (current release in https://fonts.google.com/noto)

This is a very old release. We're working on getting the latest into Google Fonts, but the problem is resolved in Noto Serif:

![shape](https://github.com/notofonts/latin-greek-cyrillic/assets/106728/a27f2079-8dbb-428d-8d60-307bf3120044)

Please get latest releases from https://notofonts.github.io (or from the releases tab of each Noto repository), or development builds from https://notofonts.github.io/latin-greek-cyrillic.

**Comment by verdy-p** [comment]
This is not "very old" given that the development version is still not deployed in the main release on its official distribution site. May be then my bug report was a reminder to Google to release updated fonts, which they didn't "since verdy long" according to your own argument that version 1.03 is "very old". Most users of Noto Fonts do not use GitHub project to get alpha/beta development versions from each subproject for specific fonts. They need a release. So this is is still not a "closed" issue" for the source which was accurately linked.

As well, not-released version of Noto fonts will still nto be part of font packs preinstalled in Android, or referenced by web sites using Google webfont servers.

When does Google plan the distribution then? Did you set milestones for releases? Note that the official Google fonts distribution site links to THIS GitHub channel, and not their own separate channel. How can we report what Google did not do for its distribution site?
